^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+$ notification=false,type=http-response,script-path=https://raw.githubusercontent.com/VTT7613VN/VTT7613VN/refs/heads/HDSHADOWROCKET/youtube_premium_logo.js
hostname = *.googlevideo.com, *.youtube.com
